name: Print hello world!
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hola-mundo:
    runs-on: ubuntu-latest
  
    steps:
      - name: checkoout repo
        id: "1"
        uses: actions/checkout@v4
      
      - name: Setup Node.js environment
        id: "2"
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Run hello
        id: "3"
        run: node index.js
