on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  my_job:
    name: run hello.js
    runs-on: ubuntu-22.04

  steps:
    name: run file
    uses: npm run ./../../hello.js
